{{- $nsqadminName := printf "%s-nsqadmin" .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $nsqadminName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $nsqadminName }}
spec:
  type: {{ .Values.nsqadmin.service.type }}
  ports:
    - port: {{ .Values.nsqadmin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $nsqadminName }}
