# Default values for golang.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enviroment: false

replicaCount: 1

image:
  repository: golang
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  containerPort: 8080
  livenessProbeEnabled: false
  livenessProbePath: /ping
  command: ""
  configMapName: ""

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

# deployment define

filebeat:
  enabled: false
  repository: filebeat
  tag: "7.10.1"
  configMapName: filebeat-conf
  logsMountPath: /wwwlogs

configmap:
  enabled: false
  payEnabled: false
  payConfName: ""

hostAliases: []
  # - ip: "192.168.1.1"
  #   hostnames:
  #     - "test1.example.com"
  #     - "test2.example.com"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

serviceAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: edge
    kubernetes.io/ingress.rule-mix: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
  #   - host: chart-example.local
  #     paths:
  #       - path: /
  #         pathType: Prefix
  # tls:
  #   - secretName: chart-example-secret
  #     hosts:
  #       - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  failureThreshold: 1
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 5
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 5
  periodSeconds: 30

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

nodeSelector: {}

tolerations: []

affinity: {}
