apiVersion: v1
kind: Service
metadata:
  name: {{ include ".Release.Name" . }}
  namespace: {{ include ".Release.Namespace" . }}
  labels:
    {{- include "golang.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "golang.selectorLabels" . | nindent 4 }}
