apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  {{- if .Values.metrics.enabled }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - name: memcached
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: memcached
    {{- if .Values.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: 9150
      targetPort: metrics
    {{- end }}
