{{- if .Values.basicAuth.enabled -}}
{{- $relname := "basic-auth" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $relname }}
  namespace: {{ .Release.Namespace }}
data:
{{- if .Release.IsUpgrade }}
  auth: {{ index (lookup "v1" "Secret" .Release.Namespace $relname).data "auth" | quote }}
{{- else }}
  auth: {{ htpasswd .Values.basicAuth.username .Values.basicAuth.password | b64enc | quote }}
type: {{ .Values.basicAuth.type }}
{{- end }}
{{- end }}
