{{- if not .Values.image.command }}
{{ $parts := split "-" .Release.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 2
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}
        group: {{ list $parts._0 $parts._1 $parts._2 | join "-" }}
        project: {{ $parts._0 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.redisPassword }}
          args: ["--requirepass", "{{ .Values.image.redisPassword }}"]
          {{- end }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: "{{ .Values.metrics.repository }}:{{ .Values.metrics.tag }}"
          imagePullPolicy: {{ .Values.metrics.pullPolicy }}
          env:
            - name: REDIS_ADDR
              value: redis://localhost:6379
            {{- if .Values.image.redisPassword }}
            - name: REDIS_PASSWORD
              value: {{ .Values.image.redisPassword }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: 9121
              protocol: TCP
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
